In [3]:
!pip install pandas numpy scikit-learn matplotlib joblib streamlit

In [4]:
import pandas
print("working")

working


In [5]:
import pandas as pd

In [6]:
df = pd.read_csv("dataset.csv")
df.head()


,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,1,18.5,95.6,3.8,97.9,A
1,2,14.0,80.0,2.5,83.9,B
2,3,19.5,86.3,5.3,100.0,A
3,4,25.7,70.2,7.0,100.0,A
4,5,13.4,81.9,6.9,92.0,A


In [7]:
df.head()

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,1,18.5,95.6,3.8,97.9,A
1,2,14.0,80.0,2.5,83.9,B
2,3,19.5,86.3,5.3,100.0,A
3,4,25.7,70.2,7.0,100.0,A
4,5,13.4,81.9,6.9,92.0,A


In [8]:
df.isnull().sum()


student_id                 0
weekly_self_study_hours    0
attendance_percentage      0
class_participation        0
total_score                0
grade                      0
dtype: int64

In [9]:
df = df.dropna()


In [10]:
df.isnull().sum()


student_id                 0
weekly_self_study_hours    0
attendance_percentage      0
class_participation        0
total_score                0
grade                      0
dtype: int64

In [15]:
import pandas as pd

df = pd.read_csv("dataset.csv")
df.head()

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,1,18.5,95.6,3.8,97.9,A
1,2,14.0,80.0,2.5,83.9,B
2,3,19.5,86.3,5.3,100.0,A
3,4,25.7,70.2,7.0,100.0,A
4,5,13.4,81.9,6.9,92.0,A


In [16]:
df.columns

Index(['student_id', 'weekly_self_study_hours', 'attendance_percentage',
       'class_participation', 'total_score', 'grade'],
      dtype='object')

In [18]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [21]:
print(df.head())

   student_id  weekly_self_study_hours  attendance_percentage  \
0           1                     18.5                   95.6   
1           2                     14.0                   80.0   
2           3                     19.5                   86.3   
3           4                     25.7                   70.2   
4           5                     13.4                   81.9   

   class_participation  total_score grade  
0                  3.8         97.9     A  
1                  2.5         83.9     B  
2                  5.3        100.0     A  
3                  7.0        100.0     A  
4                  6.9         92.0     A  


In [22]:
print(X_train.shape)
print(y_train.shape)

(800000, 5)
(800000,)


In [23]:
print(X_train.shape)
print(y_train.shape)

(800000, 5)
(800000,)


In [26]:
from sklearn.linear_model import LogisticRegression

In [27]:
model = LogisticRegression()
print("Model created")


Model created


In [28]:
model.fit(X_train, y_train)
print("Training done")

Training done


C:\Users\LEO-k\anaconda7\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [30]:
y_pred = model.predict(X_test)
print(y_pred[:10])

['D' 'A' 'B' 'A' 'B' 'B' 'B' 'B' 'A' 'A']


In [31]:
from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.638945


In [32]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, y_pred))

[[108515   1373      0      0      0]
 [ 32978  17380      0   1198      0]
 [  3812  21210    451   2907      0]
 [    41   6645    798   1443      0]
 [     0    723    273    253      0]]


In [33]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

C:\Users\LEO-k\anaconda7\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\LEO-k\anaconda7\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


              precision    recall  f1-score   support

           A       0.75      0.99      0.85    109888
           B       0.37      0.34      0.35     51556
           C       0.30      0.02      0.03     28380
           D       0.25      0.16      0.20      8927
           F       0.00      0.00      0.00      1249

    accuracy                           0.64    200000
   macro avg       0.33      0.30      0.29    200000
weighted avg       0.56      0.64      0.57    200000



C:\Users\LEO-k\anaconda7\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


In [34]:
import joblib

In [35]:
joblib.dump(model, "best_model.pkl")
print("Model saved")

Model saved
